controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/auth
    #requirements:
     #   _role: 'API_ACCESS' # L'utilisateur doit avoir acc√®s API